server:
  port: 1101
spring:
  profiles:
    active: '@env@'
  application:
    name: microservice-config-service
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        health:
          enabled: true
        git:
          search-paths: '{application}'   # 配置仓库路径下的相对搜索位置，这里使用的是项目名称作为占位符进行搜索。
          clone-on-start: true            # 启动的时候就clone Git仓库
          force-pull: true                # 如果本地副本是脏的，将使Spring Cloud Config Server强制从远程存储库拉
  security:
    user:
      name: webfuse
      password: webfuse

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dynamax-backend/dynamax-config.git
          username: xm-dev@dynamaxcn.com
          password: DynaMax@2015

---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dynamax-backend/dynamax-config.git
          username: xm-dev@dynamaxcn.com
          password: DynaMax@2015

---
spring:
  profiles: beta
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dynamax-backend/dynamax-config.git
          username: xm-dev@dynamaxcn.com
          password: DynaMax@2015

---
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dynamax-backend/dynamax-config.git
          username: xm-dev@dynamaxcn.com
          password: DynaMax@2015
