version: '3.3'
services:

  # mysql-db
  webfuse-mysql:
    image: mysql:5.7
    container_name: webfuse-mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./build/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./build/mysql/logs:/var/log/mysql:rw
      - ./build/mysql/initdb.d:/docker-entrypoint-initdb.d:ro

  # redis
#  webfuse-redis:
#    image: redis:5.0.4
#    container_name: webfuse-redis
#    ports:
#      - 6379:6379
#    expose:
#      - 6379
#    restart: always

  # rabbitmq
  webfuse-rabbitmq:
    image: rabbitmq:3-management
    container_name: webfuse-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=webfuse
      - RABBITMQ_DEFAULT_PASS=webfuse

# # registry-central
#  webfuse-central-registry:
#    build:
#      context: ./
#      dockerfile: ./central-registry/Dockerfile
#    container_name: webfuse-central-registry
#    image: webfuse-central-registry
#    restart: always
#    ports:
#      - 2000:2000
#    expose:
#      - 2000
#    environment:
#      - SPRING_PROFILES_ACTIVE=singleton

# # config-central
#  webfuse-central-config:
#    build:
#      context: ./
#      dockerfile: ./central-config/Dockerfile
#    container_name: webfuse-central-config
#    image: webfuse-central-config
#    restart: always
#    ports:
#      - 2100:2100
#    expose:
#      - 2100
#    depends_on:
#      - webfuse-mysql
#      - webfuse-central-registry



