##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
server:
  port: 7002
spring:
  application:
    name: smart-webfuse-cloud-service-zipkin-server