spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/auth
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/oauth-schema.sql
    data: classpath:db/oauth-data.sql
security:
  user:
    password: password
  oauth2:
    resource:
      id: oauth2_id
  filter-order: 5
logging:
  level:
    org.springframework: INFO
