spring:
  datasource:
    url: jdbc:mysql://rm-wz9515p648o5t6is9o.mysql.rds.aliyuncs.com/service-message?useSSL=false
    username: service_message
    password: DynaMax@2017
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 25

webfuse:
  demos:
    param_1: 1
    praram_2: 2

mybatis:
  configuration:
    map-underscore-to-camel-case: true