##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true

##########################
## 基本配置
##########################
mvc:
  favicon:
    enabled: false

webfuse-security:
  user:
    name: webfuse
    password: webfuse

---
spring:
  profiles: singleton
eureka:
  environment: dev
  server:
    enable-self-preservation: false  # 中小规模下，自我保护模式坑比好处多，所以关闭它
    renewal-threshold-update-interval-ms: 120000  # 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    eviction-interval-timer-in-ms: 5000 # 主动失效检测间隔,配置成5秒
    use-read-only-response-cache: false # 禁用readOnlyCacheMap
    wait-time-in-ms-when-sync-empty: 0  #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单机模式设置为0
  client:
    healthcheck: true
    service-url:
      defaultZone: http://${webfuse-security.user.name}:${webfuse-security.user.password}@localhost:2000/eureka/
    registry-fetch-interval-seconds: 5  # 定时刷新本地缓存时间
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false。
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
  instance:
    hostname: ${hostname:localhost}
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${server.port}    # 自定义实例ID
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10  #  没有心跳的淘汰时间，10秒
    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒
server:
  port: 2000

---
spring:
  profiles: eureka-peer-1
server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-2:2002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-3:2003/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: eureka-peer-1
    prefer-ip-address: true

---
spring:
  profiles: eureka-peer-2
server:
  port: 2002
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-1:2001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-3:2003/eureka/
    healthcheck: true
  instance:
    hostname: eureka-peer-2
    prefer-ip-address: true

---
spring:
  profiles: eureka-peer-3
server:
  port: 2003
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-1:2001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-2:2002/eureka/
    healthcheck: true
  instance:
    hostname: eureka-peer-3
    prefer-ip-address: true


