##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
spring:
  application:
    name: smart-webfuse-cloud-service-registry
  security:
    user:
      name: eureka-admin
      password: eureka-admin-pwd
  mvc:
    favicon:
      enabled: false
##########################
## eureka公共配置
##########################
##这个是多端点时候的配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-1:2001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-2:2002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-3:2003/eureka/
#  instance:
#    prefer-ip-address: true

##这个是单端点时候的配置--start
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:2001/eureka/
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false。
    fetch-registry: false #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
  instance:
    prefer-ip-address: true
server:
  port: 2001
##这个是单端点时候的配置--end
---
spring:
  profiles: eureka-peer-1
server:
  port: 2001
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: eureka-peer-1

---
spring:
  profiles: eureka-peer-2
server:
  port: 2002
eureka:
  client:
    healthcheck: true
  instance:
    hostname: eureka-peer-2

---
spring:
  profiles: eureka-peer-3
server:
  port: 2003
eureka:
  client:
    healthcheck: true
  instance:
    hostname: eureka-peer-3


