##########################
## actuator配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      enabled: true

##########################
## 基本配置
##########################
spring:
  application:
    name: smart-webfuse-cloud-service-registry
  security:
    user:
      name: eureka-admin
      password: eureka-admin-pwd
  mvc:
    favicon:
      enabled: false
##########################
## eureka公共配置
##########################
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-1:2001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-2:2002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-3:2003/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  profiles: eureka-peer-1
server:
  port: 2001
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    hostname: eureka-peer-1

---
spring:
  profiles: eureka-peer-2
server:
  port: 2002
eureka:
  client:
    healthcheck: true
  instance:
    hostname: eureka-peer-2

---
spring:
  profiles: eureka-peer-3
server:
  port: 2003
eureka:
  client:
    healthcheck: true
  instance:
    hostname: eureka-peer-3


