# 以下的port,defaultZone和hostname来自于系统启动时候传入的参数

spring:
  application:
    name: smart-webfuse-cloud-service-registry
server:
  port: ${port}

eureka:
  server:
    enable-self-preservation: false  # 中小规模下，自我保护模式坑比好处多，所以关闭它
    renewal-threshold-update-interval-ms: 120000  # 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    eviction-interval-timer-in-ms: 5000 # 主动失效检测间隔,配置成5秒
    use-read-only-response-cache: false # 禁用readOnlyCacheMap
  client:
    healthcheck: true
    service-url:
      defaultZone: ${defaultZone}
    registry-fetch-interval-seconds: 5  # 定时刷新本地缓存时间
  instance:
    hostname: ${hostname:localhost}
    instance-id: ${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}    # 自定义实例ID
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10  #  没有心跳的淘汰时间，10秒
    lease-renewal-interval-in-seconds: 5  # 心跳间隔，5秒

