##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
logging:
  level: info
server:
  port: 8080
spring:
  application:
    name: webfuse-service-starter
  cloud:
    loadbalancer:
      retry:
        enabled: true
  jackson:
    deserialization: true
    generator: true
    mapper: true
    parser: true
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: always
    serialization: true
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: @env@


---
spring:
  profiles: dev



---
spring:
  profiles: test


---
spring:
  profiles: beta


---
spring:
  profiles: prod

