##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
spring:
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true

webfuse:
  swagger2:
    project-name:
    project-version:
    project-description: