server:
  tomcat:
    uri-encoding: UTF-8
spring:
  output:
    ansi:
      enabled: detect
  profiles:
    active: @env@
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Actuator监控配置
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: beta

---
spring:
  profiles: prod
