logging:
  level:
    network.swan: DEBUG
    org.springframework: INFO

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000
  ConnectTimeout: 3000
  ReadTimeout: 3000

feign:
  compression:  # 开启请求与响应的GZIP压缩
    request:
      enabled: true
    response:
      enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true # 开启负载均衡的重试机制
    bus:
      trace:
        enabled: true #开启bus跟踪
    config:
      fail-fast: true
  rabbitmq: # 配置rabbitmq
    host: 119.23.173.116
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:12001
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30  # 续约到期时间（默认90秒）,仅在开发环境如此配置
    lease-renewal-interval-in-seconds: 10 # 续约更新时间间隔（默认30秒）,仅在开发环境如此配置
  client:
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://localhost:2101/eureka/,http://localhost:2102/eureka/  # 服务注册中心的地址
