##########################
## Actuator监控配置
##########################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    env:
      enabled: true
##########################
## 基本配置
##########################
server:
  port: 8080
spring:
  application:
    name: smart-webfuse-cloud-service-client
  cloud:
    loadbalancer:
      retry:
        enabled: true
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: @env@
##########################
## eureka配置
##########################
eureka:
  client:
    service-url:
      defaultZone: http://${webfuse.eureka-server.user.name}:${webfuse.eureka-server.user.password}@eureka-peer-1:2001/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-2:2002/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka-peer-3:2003/eureka/
  instance:
    prefer-ip-address: true
##########################
## ribbon配置
##########################
ribbon:
  OkToRetryOnAllOperations: true  #对所有操作请求都进行重试
  MaxAutoRetries: 1 #对当前实例的重试次数

---
spring:
  profiles: dev

webfuse:
  eureka-server:
    user:
      name: eureka-admin
      password: eureka-admin-pwd

---
spring:
  profiles: test

webfuse:
  eureka-server:
    user:
      name: eureka-admin
      password: eureka-admin-pwd
---
spring:
  profiles: beta

webfuse:
  eureka-server:
    user:
      name: eureka-admin
      password: eureka-admin-pwd
---
spring:
  profiles: prod

webfuse:
  eureka-server:
    user:
      name: eureka-admin
      password: eureka-admin-pwd