spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
  datasource:
    url: jdbc:h2:file:~/uaa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

mybatis:
  mapper-locations: classpath*:network/swan/service/uaa/**/repository/*.xml,classpath*:network/swan/service/uaa/**/mapper/*.xml


logging:
  level:
    org:
      springframework: INFO




